name: Release Custom ZXing

on:
  push:
    branches:
      - release

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies and build
      run: |
        yarn install
        yarn build

    - name: Clean directory and move dist files
      run: |
        find . -maxdepth 1 ! -name 'dist' ! -name '.git' ! -name '.' ! -name '..' -exec rm -rf {} \;
        mv dist/* .
        rmdir dist

    - name: Commit and push changes
      run: |
        git remote set-url origin https://github-actions:${{ secrets.GH_TOKEN }}@github.com/trapedev/ts-zxing
        git config --global user.name "actions"
        git config --global user.email "actions@users.noreply.github.com"
        if (git diff --shortstat | grep '[0-9]'); then \
          git add .; \
          git commit -m "Release"; \
          git push origin HEAD:${GITHUB_REF}; \
        fi